# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            sumnoise


paginate:         5

author:
  name: 'David McCormick'
  email: 'david@sumnoise.com'