port: 3000

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: sumnoise
paginate: 5

author:
  name: 'David McCormick'
  email: 'david@sumnoise.com'

# Gems
gems: [jekyll-paginate]
