title:        Sumnoise
url:          http://davidpmccormick.github.io
version:      1.1.1
author:
  name:       'DMC'
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
